[package]
name = "mp"
version = "0.1.0"
authors = ["Hiro Kojima <guitarsaiko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rand = "0.8.3"
chrono = "0.4"
regex = "1.5"